version: '2'

services:
  db:
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: changeme
    restart: always
    image: postgres:9.6
  redis:
    restart: always
    image: redis:3.0
  elasticsearch:
    image: elasticsearch:2.3
    restart: always
  app:
    environment:
      DJANGO_SECRET_KEY: changeme
      DATABASE_URL: postgres://app_user:changeme@db/app_db
      CACHE_URL: redis://redis
      ELASTICSEARCH_ENDPOINT: elasticsearch
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - media-root:/code/bakerydemo/media
    links:
      - db:db
      - redis:redis
      - elasticsearch:elasticsearch
    labels:
      - traefik.http.services.wagtail.loadbalancer.server.port=8000
      - traefik.http.routers.wagtail.rule=Host(`wagtail.alexisig.com`)
      - traefik.http.routers.wagtail.tls.certresolver=le
    depends_on:
      - db
      - redis
      - elasticsearch
volumes:
  media-root:
